TARGET = libyajl
DLLIB = $(TARGET).so
all:

install:
	mkdir -p /home/schneiderz/test/chef-cascade/.gems/gems/libyajl2-1.2.0/lib/libyajl2/vendored-libyajl2/lib
	cp $(DLLIB) /home/schneiderz/test/chef-cascade/.gems/gems/libyajl2-1.2.0/lib/libyajl2/vendored-libyajl2/lib/$(DLLIB)
	mkdir -p /home/schneiderz/test/chef-cascade/.gems/gems/libyajl2-1.2.0/lib/libyajl2/vendored-libyajl2/include/yajl
	cp yajl/*.h /home/schneiderz/test/chef-cascade/.gems/gems/libyajl2-1.2.0/lib/libyajl2/vendored-libyajl2/include/yajl
